#!/bin/bash

cd payment-service
./gradlew bootJar
cd ..
cd orders-service
./gradlew bootJar
cd ..
cd warehouse-service
./gradlew bootJar
cd ..
cd eureka-server
./gradlew build
cd ..

docker-compose up --force-recreate