version: '3.4'
services:
  
  eureka:
    build: ./eureka-server
    ports:
      - "8761:8761"
    restart: on-failure

  payment:
    build: ./payment-service
    volumes:
      - ./payment-service/data:/data
    ports:
      - "9002:9002"
    depends_on:
      - rabbitmq
      - eureka
    restart: on-failure

  orders:
    build: ./orders-service
    volumes:
      - ./orders-service/data:/data
    ports:
      - "9000:9000"
    restart: on-failure
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=bitnami
    depends_on:
      - rabbitmq
      - eureka

  warehouse:
    build: ./warehouse-service
    volumes:
      - ./warehouse-service/data:/data
    ports:
      - "9001:9001"
    restart: on-failure

    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=bitnami
    depends_on:
      - orders
      - rabbitmq
      - eureka

  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    build: ./rabbitmq
    ports:
      - '4368:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'

  api-gateway:
    build: ./api-gateway
    ports:
      - "8111:8111"
    depends_on:
      - rabbitmq
      - eureka
    restart: on-failure